#!/bin/bash
DATE=$(date +%Y%m%d)
FORTUNE=$(fortune -s|sed 's/"//g')
  DOCKER_ICINGA2_UPDATED=20160104

git pull
sed -i "s/^\ \ DOCKER_ICINGA2_UPDATED=.*$/ENV DOCKER_ICINGA2_UPDATED=$DATE/" Dockerfile
git commit -am "$FORTUNE -- $DATE"
